# Generated by Django 3.1.3 on 2020-11-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0002_auto_20201125_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorposition',
            name='geo_uri',
        ),
        migrations.AddField(
            model_name='sensorposition',
            name='coordinate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='road_utilization.coordinate'),
            preserve_default=False,
        ),
    ]
