# Generated by Django 3.1.3 on 2020-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0006_roadutilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='count_car',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='count_truck',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='vehicle_9',
            field=models.IntegerField(default=0),
        ),
    ]
