# Generated by Django 3.1.3 on 2020-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0007_auto_20201127_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=0, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_1',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_2',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_3',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_4',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_5',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_6',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_7',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_8',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='vehicle_9',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='data',
            field=models.ManyToManyField(to='road_utilization.KeyValuePair'),
        ),
    ]
