# Generated by Django 3.1.3 on 2020-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0009_cyclemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclemapping',
            name='cycle_time',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
