# Generated by Django 3.1.3 on 2020-11-28 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0010_auto_20201127_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorposition',
            name='coordinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='road_utilization.coordinate'),
        ),
        migrations.AlterField(
            model_name='sensorposition',
            name='road_stretch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='road_utilization.roadstretch'),
        ),
    ]
