# Generated by Django 3.1.3 on 2020-11-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0011_auto_20201128_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluepair',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
