# Generated by Django 3.1.3 on 2020-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_utilization', '0012_auto_20201128_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadutilization',
            name='count_cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadutilization',
            name='count_trucks',
            field=models.IntegerField(default=0),
        ),
    ]
